### ISSUE TITLE
handling of int attributes

### ISSUE THREAD

**Issue by jmdcal** [leforestier/yattag#10]
How to handle integer attributes? the `attr_escape` function fails. I have a patch if you want.

**Comment by leforestier** [comment]
I don't think it's too much of a problem.
You should just convert integers to strings:
```python
number = 42
with tag('div', id = str(number)):
    ...
```

**Comment by jmdcal** [comment]
good point. my bad. I thought that integers would not be quoted, but they must be. Thanks for your feedback.
