### ISSUE TITLE
Add non-keyword/bare/string attributes to tags without Doc.asis

### ISSUE THREAD

**Issue by AndydeCleyre** [leforestier/yattag#19]
Hi,

Thanks for working on yattag! Is it currently possible to add non-keyword attributes to tags? 

Something like:

```python
with tag('paper-button', 'raised'):
    text('I am a fancy button')
````

and have it render to:

```html
<paper-button raised>
    I am a fancy button
</paper-button>
````

The best I can figure out right now is just dropping the whole html block into a `Doc.asis` call.

**Comment by leforestier** [comment]
Hi Andy,

what about writing:
```html
<paper-button raised="raised">
    I am a fancy button
</paper-button>
```
since they are equivalent ?

**Comment by leforestier** [comment]
I actually added the feature. Exactly as you suggested, you can now write:

```python
with tag('paper-button', 'raised'):
    text('I am a fancy button')
````
and get:

```html
<paper-button raised>
    I am a fancy button
</paper-button>
````

**Comment by AndydeCleyre** [comment]
Thanks, that's great!
