### ISSUE TITLE
Exception in Doc.getvalue()

### ISSUE THREAD

**Issue by little-dude** [leforestier/yattag#20]
First of all thanks for this excellent library.

I'm sometimes running into the following issue when calling `Doc.getvalue()` (the "stacktrace" is taken from django error page).

```
Exception Type:	TypeError
Exception Value:	
sequence item 12: expected string or Unicode, NoneType found
Exception Location:	/home/corentih/django/pygashreporter/env/lib/python2.7/site-packages/yattag/doc.py in getvalue, line 431
Python Executable:	/home/corentih/django/pygashreporter/env/bin/python
Python Version:	2.7.9

/home/corentih/django/pygashreporter/env/lib/python2.7/site-packages/yattag/doc.py in getvalue

424        """
425        returns the whole document as a string
426        """
427        for position, render_function in self._detached_errors_pos:
428            self.result[position] = render_function(
429                dict((name, self.errors[name]) for name in self.errors if name not in self._fields)
430            )
431                    return ''.join(self.result) ...  
 ```

The script that makes this happen is quite complex and so far I've been unable to find a simple way to reproduce. Do you want me to provide the script, or can you see what's happening from this error message?

Meanwhile, I "fixed" the issue by changing the returned value : 

```python
return ''.join([x for x in self.result if x is not None])
```

PS : apologies for such poor bug report. I'll try to dig into this to reproduce with a simple case.

**Comment by leforestier** [comment]
It seems you added a None value instead of a string somewhere in the document.
Check your `doc.asis(...)` calls. Maybe you wrote a function that forgets to return a value and passed its result to `Doc.asis`.
You can do a `print(doc.result)` to see at what point the None value was added.

**Comment by little-dude** [comment]
Indeed I found where is the code I was passing `None`, thanks.
Maybe `asis` should raise an exception when it's passed a `None` value? That way it would be easy to see where it happening.

I can do the PR for that.

**Comment by leforestier** [comment]
I agree. I think that would make sense to raise a TypeError in this situation.
