### ISSUE TITLE
copyright/licence clarification

### ISSUE THREAD

**Issue by sandrotosi** [leforestier/yattag#25]
I'm packaging yattag for Debian, but to do that I need some  clarification on:

- copyright: you dont claim any copyright on the module source code, could you provide a minimal copyright stanza?

- license: in the PyPI trove you claim it's LGPL, but there are multiple versions of LGPL out there (namely 2, 2.1, 3) - with which version yattag is licensed?

thanks!

**Comment by leforestier** [comment]
Hi,

I'm going to go with the LGPL 2.1 as it seems to be the most permissive and flexible according to this table: https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility .
I'm going to add the files shortly.

**Comment by sandrotosi** [comment]
thanks a ton, Benjamin!
