### ISSUE TITLE
provide the test in the pypi tarball

### ISSUE THREAD

**Issue by sandrotosi** [leforestier/yattag#27]
i see in the git repo there is a directory 'tests' with some tests: could you added them to the pypi tarball, so that we can run them when we install the module locally and verity all is good? thanks!

**Comment by leforestier** [comment]
Done. It doesn't appear on github yet because they lag tonight (see https://status.github.com/ )
But it's already on Pypi (version 1.5.3) along with the license files: https://pypi.python.org/pypi/yattag

**Comment by leforestier** [comment]
https://github.com/leforestier/yattag/commit/8f81f960ca1b6e227028465f174d091c4436a231
