### ISSUE TITLE
numpy.float64' object has no attribute 'add_format'

### ISSUE THREAD

**Issue by TioSJ** [leforestier/yattag#31]
import pandas as pd
    import numpy as np
    def draw_table(request):
    dt = pd.read_excel(excel path)    
    def color_green (color):
        A1= df.iloc[4,0]
        A2= df.iloc[4,1]
        if A1<A2:
            format=A2.add_format({'bg_color': 'red'})
            return (format)
        else:
            format = A2.add_format({'bg_color': 'green'})
            return (format)
    table2=table1.style.applymap(color_green).set_table_attributes('border="" class = "dataframe table table-hover table-bordered"').set_precision(10).render()

    print(table2)
    context = {

         "result": b+ table2
    }
    return render(request, 'result.html',context)

anyone have idea on the return code which is 
           format = A2.add_format({'bg_color': 'green'})
            return (format)

**Comment by leforestier** [comment]
Hi,

you don't seem to be using yattag in this example. Your question seems to be about Pandas. You should ask it on stackoverflow, unless you want to report a bug in Pandas, then you should ask it here https://github.com/pandas-dev/pandas
