### ISSUE TITLE
Add support for all posible attributes which names are reserved words in Python

### ISSUE THREAD

**Issue by nomad-vagabond** [leforestier/yattag#40]
Obviously, `class` is not the only reserved word in Python. Some attributes of html elements might have such names as `for`, `in`, `with`, etc. 

To deal with all possible conflicts I propose to implement a common solution, based on adding underscore to the names of attributes, which are reserved words in Python.

I personally use `for` attribute in the `label` tag. Thus, with the proposed improvement I would specify `_for` in the definition of the tag, which will be processed by yattag as `for`.

**Comment by nomad-vagabond** [comment]
Didn't know about (key, value) option. Thanks! 

Still, the underscore shielding seems to be more elegant solution from my point of view. If you find it a useful feature I can come out with a pull request.  By now I close the issue.

**Comment by SeanFromIT** [comment]
Can we call this out a little better in the tutorial?
