### ISSUE TITLE
Support for XML Processing instructions

### ISSUE THREAD

**Issue by zuskavit** [leforestier/yattag#41]
I am using yattag to generate and indent DITA (xml) key maps and ditaval files... I recently had to add a reference to a CSS stylesheet into all the xml files, something like this:

`doc.asis('<?xml-stylesheet type="text/css" href="..\..\..\..\..\..\..\SharedResourceFiles\MAIN\Stylesheets\CSS\dita_branded_preview.css" title="Branded New"?>')`

This resulted into an XMLTokenError - Unrecognized XML token near ....

I got around this by adding the following code to indentation.py in the yattag folder:
```python
class Stylesheet(Token):   
    regex = r'''<\?xml-stylesheet\s+[\w\\/". =]*\?>'''
```

I also had to add Stylesheet to the tokenize declaration:
```python
tokenize = Tokenizer(
    (Text, Comment, Stylesheet, CData, Doctype, XMLDeclaration, Script, Style, OpenTag, SelfTag, CloseTag)
).tokenize
```

Could you please provide a more generic solution to deal with xml processing instructions?

Thank you.

Disclaimer: This is my first time on github. I am also not a Python expert, nor an xml expert, I work as a Technical Author.

**Comment by leforestier** [comment]
Hi,

thanks for bringing this to my attention. 
At first sight, I think we'd just have to do what you did, but instead of creating a `Stylesheet` token, we would create a `ProcessingInstruction` token that would be more general.
I'm going to look into this.
