### ISSUE TITLE
Enabling support for file type in input field.

### ISSUE THREAD

**Issue by piyush-multiplexer** [leforestier/yattag#42]
file is missing from following types in input fields in original code, so it throws error

> yattag.simpledoc.DocError: Unknown input type: file

    def input(self, *args, **kwargs):
        "required attributes: 'name' and 'type'"
        name, type, attrs = _attrs_from_args(('name', 'type'), *args, **kwargs)
        self._fields.add(name)
        if type in (
            'text', 'password', 'hidden', 'search', 'email', 'url', 'number',
            'range', 'date', 'datetime', 'datetime-local', 'month', 'week',
            'time', 'color', 'file'
        ):

**Comment by leforestier** [comment]
Issue finally settled thanks to https://github.com/leforestier/yattag/pull/63
