### ISSUE TITLE
Method to get version of the library

### ISSUE THREAD

**Issue by ogroef** [leforestier/yattag#47]
Hi

Is there a method to retrieve the library version.
I am using your lib in my project, and I list all used library with there version.
Now I hardcode the version of the lib, but it would be nice to retreive the version from the lib.

Regards
Olivier

**Comment by leforestier** [comment]
Hi,

```python
import yattag
print(yattag.__version__)
```
Is this what you were looking for?

**Comment by ogroef** [comment]
This returns `None` for me
