### ISSUE TITLE
Add declaration

### ISSUE THREAD

**Issue by kenahoo** [leforestier/yattag#49]
Is there a way to add a declaration at the top of an XML document I'm generating, e.g. `<?xml version="1.0" encoding="UTF-8"?>`?

**Comment by jacobluke121** [comment]
Hi there, 

I think this could work. 

def build(textBlock):
    """
    builds the html 

    """
    doc, tag, text = Doc().tagtext()
    doc.asis(textBlock)
    return doc.getvalue()

xmlBlock = "whatever you want it to be"
build(xmlBlock)

The 'asis' method basically means it take the variable in as it comes. 

Let me know if this works.

**Comment by leforestier** [comment]
@jacobluke121: while it's true that the `asis` method should be used here, your example looks like it would always return the same string (just the XML declaration). 

@kenahoo: so, yes, use the `asis` method. There's an example in the tutorial about adding a HTML doctype, and it's the same for XML declarations: https://www.yattag.org/#appending-strings-as-is

**Comment by jacobluke121** [comment]
@leforestier thanks for pointing this out. This makes sense.
