### ISSUE TITLE
Shorter / more elegant implementation of some of the features

### ISSUE THREAD

**Issue by bckpkol** [leforestier/yattag#57]
Yattag in 57 LOC:
https://gist.github.com/bckpkol/f2a19219e4ab0579970ea888dfada714

**Comment by leforestier** [comment]
Hello,

I modified the title of the issue as it lacked courtesy.

Yes the code is a bit convoluted for what it does. I wrote this code about 8 years ago and I published it on github about 6 years ago. If I were to write this code today I'd write it in a simpler way.

However this code works, it has tests, it has been working for 8 years for me in various settings, and it has been working for so many people during the last 6 years that I don't see the point in rewriting what has now been tested by time.

Now did you really achieve a great improvement with your 54 lines of code?

You apparently reimplemented part of what is contained in my simpledoc.py file.
The main point of yattag originally was to deal with HTML forms rendering, this is in doc.py and your code doesn't help with that at all.
Now, if I remove from simpledoc.py:
- the docstrings (your code has none)
- the typing annotations (your code doesn't have these)
- the features that your code doesn't implement (a lot of these have been requested by users along the years):
    - the attr, asis, stag, data, cdata, line, ttl methods
    - allowing people to specify xml attributes that aren't valid python identifiers using (key, value) pairs
    - allowing people to specify html attributes with no value
    - allowing people to specify ints or floats as attribute values, or as the text content of a XML node
    - the methods that deal with setting/toggling css classes
    - the option that deals with transforming new lines into `<br>`  tags
    - the option that deals with choosing how singleton tags should end (xml style vs html5 style)    
    
So if I remove all the lines in simpledoc.py that deal with the above and that your code doesn't address, I'm down to 65 lines of code. Not sure if doing it in 54 lines was worth raising an issue here. Clearly not worth replacing the existing code in my opinion.

**Comment by bckpkol** [comment]
Docstrings, typing annotations - I agree, but they are often rather misleading.
XHTML vs HTML5, well, I planned to add that later. I just sticked with XHTML by default.
Also, you do not convert tags and attributes to lowercase, which is a missing feature.
My code had two more features than yours. You could:
`doc, tag, text = Doc()`
instead of
`doc, tag, text = Doc().tagtext()`
and
`print(doc)`
instead of
`print(doc.getvalue())`.

> allowing people to supply html attributes with no value
> allowing people to supply ints or floats as attribute values, or as the text content of a XML node
> the methods that deal with setting/toggling css classes
> the option that deals with transforming new lines into <br> tags

Bloated to 60 LOC.

> the attr, asis, stag, data, cdata, line, ttl methods
> allowing people to supply xml attributes that aren't valid python identifiers using (key, value) pairs

Will implement when I'll have time to dig.
