### ISSUE TITLE
The readme could mention github.com/Knio/dominate as a related project 🤔

### ISSUE THREAD

**Issue by lucasea777** [leforestier/yattag#61]

**Comment by leforestier** [comment]
Thanks for the suggestion but I'm not going to do that. The readme is very short: it contains just two examples, and it links to only one external page (yattag.org). It would be confusing to add a link to another project. And if people found Yattag they probably don't need Dominate.
By the way, despite the similar use of `with` blocks, Dominate is not related to Yattag.
