### ISSUE TITLE
indent() function memory error

### ISSUE THREAD

**Issue by nosalan** [leforestier/yattag#64]
For a large HTML, when passed to indent function it throws `MemoryError`:
```
...
 File "C:\Python382\lib\site-packages\yattag\indentation.py", line 361, in indent
    _indent()
  File "C:\Python382\lib\site-packages\yattag\indentation.py", line 341, in _indent
    append(indentation)
MemoryError
```
This is how I use the function:
```
        result = indent(
            self.doc.getvalue(),
            indentation='    ',
            newline='\n',
            indent_text=False
        )
```

The doc is quite large (150M) but there is 20 gigs of free RAM which is still insufficient

**Comment by leforestier** [comment]
Hello,
how deep is the document in terms of nested tags? Is it possible for you to send me a link to this document?

**Comment by nosalan** [comment]
It isn't particularly deep. Here is the HTML that caused problem. It is already indented on a machine with more RAM
https://drive.google.com/file/d/1bYUVRFXPmgUfcyf1kA_aeyT5rDx-g7ZC

**Comment by leforestier** [comment]
I tested on my laptop that has 16G of RAM and got no problem.
Then I ran the official python docker image in a container using the `-m` option of docker to limit the amount of RAM used by the container. Using only 2G of RAM, your document is indented without problem. I was also monitoring the memory using the top utility to make sure this docker option is really a hard limit on memory usage and it is.

It breaks when using 1G of RAM for the container, though. This could probably be improved but that doesn't seem nearly as bad as what you describe.

Can you make more tests on your original machine? Maybe you were storing many big documents in a list and they weren't garbage collected?
