### ISSUE TITLE
Please add a license for this project

### ISSUE THREAD

**Issue by JVillella** [leforestier/yattag#66]
What is the license for this open-source project? I'd like to use it in personal and commercial projects.

**Comment by JVillella** [comment]
Looks like it's LGPL, just no licence file provided w/ the project.

**Comment by leforestier** [comment]
There's a license file included in the project: https://github.com/leforestier/yattag/blob/master/license/lgpl-2.1.txt
This license file is part of the package that's downloaded when you install yattag using pip.
And yes, you're free to include yattag in personal or commercial projects.

**Comment by JVillella** [comment]
Thanks, somehow I missed it :) Was looking for a top-level LICENSE.txt
