### ISSUE TITLE
indent error for very long string 

### ISSUE THREAD

**Issue by Guang91** [leforestier/yattag#70]
Hi, 

I'm trying to do a "indent(doc.getvalue())" but got an error:
Unrecognized XML token near '<!DOCTYPE html><html lang="en"><head><meta http-equiv="content-type" content="text/html; charset=utf'
I realized this is caused by the length of doc.getvalue(). For shorter strings, the error doesn't occur. 

Thanks,
Guang

**Comment by leforestier** [comment]
Hi Guang,
can you make a small example where indent doesn't work and post it here? If your HTML string is too long, I suggest you post the python code that generated it rather than the HTML itself.
Thanks.

**Comment by Guang91** [comment]
Thanks for the quick reply. 
After some tests, I realized that's not related to the length of the string. It's just because the html has some text of "1.0 < z < 2.2", that indent doesn't know how to interpret. After removing this text (which is okay for me), it runs through. 

Thank you,
Guang
