### ISSUE TITLE
Provide way to not escape attribute values

### ISSUE THREAD

**Issue by abingham** [leforestier/yattag#81]
I have a situation where I need to pass some structured data via an attribute. Here I'm specifying HTMX configuration through the `content` attribute:
```
doc.stag("meta", name="htmx-config", content='{"scrollBehavior":"auto"}')
```

Unfortunately, it seems that attribute contents get unilaterally escaped in `simpledoc.attr_escape()`, so that attribute value comes out mangled as `<meta name="htmx-config" content="{&quot;scrollBehavior&quot;:&quot;auto&quot;}" />`. 

I don't see any mechanism to avoid this beyond, perhaps, using `doc.asis()`. Would you consider adding a means to avoid escaping attribute values? Perhaps something like this:
```
from yattag import AsIs
...
doc.stag("meta", name="htmx-config", content=AsIs('{"scrollBehavior":"auto"}'))
```

With this, `attr_escape` could look for instances of `AsIs` and not escape them. Perhaps there are other, better ways, but this is one option.

**Comment by abingham** [comment]
If it helps, I could probably put together a PR.

**Comment by leforestier** [comment]
What would you like the HTML output to be in that example?

**Comment by abingham** [comment]
Something like this: `<meta name="htmx-config" content='{"scrollBehavior":"auto"}'/>`
